version: "3.8"

services:
  libretranslate:
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    ports:
      - "${HOST_PORT:-5000}:5000"
    command: [ "--host", "0.0.0.0" ]
